from pysplicing import *
MISO_START_AUTO=0L
MISO_START_UNIFORM=1L
MISO_START_RANDOM=2L
MISO_START_GIVEN=3L
MISO_START_LINEAR=4L
# stop after fixed no. iterations
MISO_STOP_FIXEDNO=0L
MISO_STOP_CONVERGENT_MEAN=1L
# various algorithms
MISO_ALGO_REASSIGN=0L
MISO_ALGO_MARGINAL=1L
MISO_ALGO_CLASSES=2L
