
from pysplicing import *
from GFF import *

MISO_START_AUTO=1L
MISO_START_UNIFORM=2L
MISO_START_RANDOM=3L
MISO_START_GIVEN=4L
MISO_START_LINEAR=5L

MISO_STOP_FIXEDNO=1L
MISO_STOP_CONVERGENT_MEAN=2L

